server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://101.37.66.239:3306/hao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT


mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true



logging:
  level:
    com:
      example:
        mapper : debug